function(CHECK_COMPILER)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(is_clang true PARENT_SCOPE)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(is_gcc true PARENT_SCOPE)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(is_msvc true PARENT_SCOPE)
  endif()
endfunction()
